DT-425 Migrated Swell-foot to Core22/Gnome42
ubuntu/swell-foop pull request #4
Opened 2022-08-01 09:53 UTC by sergio-costas

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please check only the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

**Test Configuration**:

* OS (please include version):
* Any other relevant environment information:

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

2022-08-12 22:28 UTC, hellsworth requested changes

2022-08-12 22:28 UTC, hellsworth commented on snapcraft.yaml
> +  snapcraft-preload:
Why is this part needed?

2022-08-12 22:28 UTC, hellsworth commented on snapcraft.yaml
> +      craftctl set version=$(git describe --tags --abbrev=10)
Since [the release version is in the appdata file](https://gitlab.gnome.org/GNOME/swell-foop/-/blob/master/data/org.gnome.SwellFoop.appdata.xml.in#L41), I think we can remove this line.

2022-08-30 11:40 UTC, sergio-costas commented on snapcraft.yaml
> +  snapcraft-preload:
It is because it uses the clutter library. Without that, it shows a blank window.

2022-08-30 11:46 UTC, sergio-costas commented on snapcraft.yaml
> +      craftctl set version=$(git describe --tags --abbrev=10)
Done.

2022-08-31 02:59 UTC, hellsworth approved these changes
Looks great, thanks!

2023-05-24 20:37 UTC, merged